# Dockerfile for python-app
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy requirements first (for caching)
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the source code
COPY . .
COPY .env /app/.env

# Default command: run your app
CMD ["python", "main.py"]
